/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.time.LocalDate;
import persistence.DataBase;

/**
 *
 * @author ignacio
 */
public class InicioFechaRegistroFacturaJTable extends javax.swing.JFrame {

    private MainFrame mainFrame;

    /**
     * Creates new form InicioFechaRegistroFacturaFrame
     */
    public InicioFechaRegistroFacturaJTable(MainFrame mainFrame) {
        initComponents();
        this.mainFrame = mainFrame;
        mainFrame.setVisible(false);
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMonthChooser = new com.toedter.calendar.JMonthChooser();
        jYearChooser = new com.toedter.calendar.JYearChooser();
        jLabel1 = new javax.swing.JLabel();
        cancelarButton = new javax.swing.JButton();
        aceptarjButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMonthChooser.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N

        jYearChooser.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Elige mes y año de inicio");

        cancelarButton.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        cancelarButton.setText("Cancelar");
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });

        aceptarjButton.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        aceptarjButton.setText("Aceptar");
        aceptarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jMonthChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jYearChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(cancelarButton)
                        .addGap(18, 18, 18)
                        .addComponent(aceptarjButton)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jMonthChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jYearChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aceptarjButton)
                    .addComponent(cancelarButton))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
        dispose();
        mainFrame.setVisible(true);
    }//GEN-LAST:event_cancelarButtonActionPerformed

    private void aceptarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarjButtonActionPerformed
        LocalDate fechaInicioRegistroFactura = LocalDate.of(jYearChooser.getValue(), jMonthChooser.getMonth() + 1, 1);
        DataBase.insertRegistroFactura(mainFrame.getArrendatario().getDni(), mainFrame.getInmueble().getIdInmueble(), 1, fechaInicioRegistroFactura, false, false, false, mainFrame.getContrato().getIdContrato());
        mainFrame.rellenarTablaRegistroFactura(DataBase.selectRegistroFacturaByDniArrendatarioAndIdInmueble(mainFrame.getArrendatario().getDni(), mainFrame.getInmueble().getIdInmueble()));
        mainFrame.getFechaInicioTextField().setText(fechaInicioRegistroFactura.plusMonths(1).toString());
        mainFrame.getFechaFinTextField().setText(fechaInicioRegistroFactura.plusMonths(mainFrame.getNumeroMesesSpinner()).toString());
        mainFrame.setUltimoRegistroFactura(DataBase.selectRegistroFacturasUltimaFechaFacturaFacturaByDniArrendatarioAndIdInmueble(mainFrame.getArrendatario().getDni(), mainFrame.getInmueble().getIdInmueble()));
        dispose();
        mainFrame.setVisible(true);
    }//GEN-LAST:event_aceptarjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarjButton;
    private javax.swing.JButton cancelarButton;
    private javax.swing.JLabel jLabel1;
    private com.toedter.calendar.JMonthChooser jMonthChooser;
    private com.toedter.calendar.JYearChooser jYearChooser;
    // End of variables declaration//GEN-END:variables
}