/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

/**
 *
 * @author ignacio
 */
public class MainFrame2 extends javax.swing.JFrame {
    
    private MainFrame mainFrame;
    /** Creates new form MainFrame2 */
    public MainFrame2(MainFrame mainFrame) {
        initComponents();
        this.mainFrame = mainFrame;
        setVisible(true);
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        taxjButton = new javax.swing.JButton();
        modelosContratojButton = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        taxjButton.setText("Impuestos");
        taxjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taxjButtonActionPerformed(evt);
            }
        });

        modelosContratojButton.setText("Modelos contrato");
        modelosContratojButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelosContratojButtonActionPerformed(evt);
            }
        });

        jButton4.setText("Volver");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jButton4)
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(0, 23, Short.MAX_VALUE)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                .add(taxjButton)
                                .add(49, 49, 49))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                .add(modelosContratojButton)
                                .add(29, 29, 29))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(taxjButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(modelosContratojButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jButton4)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void taxjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taxjButtonActionPerformed
        setVisible(false);
        new view.Configuracion(this);
    }//GEN-LAST:event_taxjButtonActionPerformed

    private void modelosContratojButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelosContratojButtonActionPerformed
        setVisible(false);
        new ModelosContrato(this);
    }//GEN-LAST:event_modelosContratojButtonActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        mainFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    public MainFrame getMainFrame(){
        return this.mainFrame;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton modelosContratojButton;
    private javax.swing.JButton taxjButton;
    // End of variables declaration//GEN-END:variables

}
